force-app/main/default/objects/User_Info__c/User_Info__c.object-meta.xml
<CustomObject>
    <label>User Info</label>
    <nameField>
        <label>User Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Info__c/fields/Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Active_Users__c</fullName>
    <label>Active Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrgInfo_Controller.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-01-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class OrgInfo_Controller {
    
    @AuraEnabled(cacheable = true)
    public static List<User_Info__c> getActiveUsers() {
        List<User> users = new List<User>();
        users = [Select Id from User where IsActive = true];
        decimal size = users.size();
        system.debug('Count::::' +size);
        
        integer count = Integer.valueOf(size);
        User_Info__c usersInfo = new User_Info__c();
        usersInfo = [Select Id,Active_Users__c  from User_Info__c where Name = 'Org Info Record'];
        usersInfo.Active_Users__c = count;
        update usersInfo;

        List<User_Info__c> userList = new List<User_Info__c>();
        userList = [Select Id, Name, Active_Users__c from User_Info__c where Name = 'Org Info Record'];
        
        return userList;
    }
}