force-app/main/default/objects/Income__c/Income__c.object-meta.xml
<CustomObject>
    <description>For Income Calculator LWC Component</description>
    <label>Income</label>
    <nameField>
        <label>Income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/fields/Amount_Source__c.field-meta.xml
<CustomField>
    <fullName>Amount_Source__c</fullName>
    <label>Amount Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Income__c/fields/Next_Expected_Interest__c.field-meta.xml
<CustomField>
    <fullName>Next_Expected_Interest__c</fullName>
    <label>Next Expected Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Income__c/fields/Total_Principal__c.field-meta.xml
<CustomField>
    <fullName>Total_Principal__c</fullName>
    <label>Total Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/IncomeCalculatorController.cls
/**
 * @description       : 
 * @author            : Jaya Prakash Merepala
 * @group             : 
 * @last modified on  : 07-05-2024
 * @last modified by  : Jaya Prakash Merepala
**/
public with sharing class IncomeCalculatorController {
    public static Integer totalPrincipal() {
        Integer principal = 0;
        List<Income__c> incomeList = new List<Income__c>();
        incomeList = [Select Id,Name,Amount__c,Amount_Source__c,Interest__c,Next_Expected_Interest__c,Total_Principal__c From Income__c WITH SECURITY_ENFORCED];


        for(Income__c inc : incomeList) {
            if(inc.Total_Principal__c != null) {
                principal += Integer.valueOf(inc.Total_Principal__c);
            }
        }

        return principal;
    }
}