force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Need_Isolation__c.field-meta.xml
<CustomField>
    <fullName>Need_Isolation__c</fullName>
    <label>Need Isolation?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Need_Medication__c.field-meta.xml
<CustomField>
    <fullName>Need_Medication__c</fullName>
    <label>Need Medication?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/candidateTriggerHandler.cls
public class candidateTriggerHandler {
    
    public void OnBeforeInsert(List<Candidate__c> candList){
        
        List<Candidate__c> candidatesList = new List<Candidate__c>();
        
        for(Candidate__c c : candidatesList){
            if(c.COVID_Positive__c = TRUE){
                c.Need_Isolation__c  = 'Yes';
                c.Need_Medication__c = 'Yes';
            }
        }
    }
    
    public  void OnBeforeUpdate(List<Candidate__c> candList){
        
        List<Candidate__c> candidateList = new List<Candidate__c>();
        
        for(Candidate__c cd : candidateList){
            if(cd.COVID_Positive__c = TRUE){
                cd.ORF1ab_Gene_CT_Value__c.addError('This value shouldnt be blank.');
            }
        }
    }
    public static void OnAfterInsert(List<Candidate__c> candidateList, Map<Id,Candidate__c> candMap){
        
        List<Candidate__c> newList = new List<Candidate__c>();
        List<Case> caseList = new List<Case>();
        
        Map<Id,Candidate__c> candWithCase = new Map<Id,Candidate__c>
            ([Select Id, Name, Case__c from Candidate__c where Id IN :newList]);
        
        for(Candidate__c c : newList){
            if(String.isBlank(c.Case__c)){
                caseList.add(new Case(Status = 'New',
                                      Origin = 'Phone',
                                      Subject  = c.Name + 'Case'));
            }
            
        }
        insert caseList;
    }
    
    public static void OnAfterUpdate(List<Contact> contactList){
        
        List<Contact> conList = new List<Contact>();
        
        for(Contact cont : conList){
            if(cont.Candidate__c <> Null){
                cont.Description = 'Updated';
            }
        }
    }
}