force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/fields/Next_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Notification_Date__c</fullName>
    <label>Next Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/fields/Refresh_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Due_Date__c</fullName>
    <label>Refresh Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RefreshEmailNotification.cls
public class RefreshEmailNotification implements Database.Batchable<sObject> {
    
    public database.QueryLocator Start(Database.BatchableContext BC)
    {
        //for(Questionnaire__c updateNotificatios : [Select ID, Name, Refresh_Due_Date__c, Status__c, Next_Notification_Date__c from Questionnaire__c
        //                                          Where Refresh_Due_Date__c > TODAY() AND Refresh_Due_Date__c <> NULL ])
        
        return Database.getQueryLocator([Select ID, Name, Refresh_Due_Date__c, Status__c, Next_Notification_Date__c 
                                         From Questionnaire__c
                                         ]);
    }
    public void execute(Database.BatchableContext BC, List<Questionnaire__c> scope)
    {
        system.debug('list of questionnaires:' +scope);
        
        //update the next notificatio date 
        for (Questionnaire__c que : scope)
        {
            if(que.Refresh_Due_Date__c != NULL){
                
                RefreshEmailNotificationBatchHelper.daysOutFifteen(scope);
            }
        }
        update(scope);
        /*for (Database.SaveResult sr : scope){
            if(sr.isSuccess()){
                system.debug('list of updated records:'+sr.getId());
            }
        } */
    }
    public void finish(Database.BatchableContext BC){
        
    }
    
}